name: Develop Branch Workflow

on:
  push:
    branches: [ develop ]
    paths-ignore:
    - '**/*.md'
    - 'LICENSE'
    - '.gitignore'
    
jobs:
  Build-Test-Deploy:
    runs-on: ubuntu-latest
    environment:
      name: Dev
      url: https://ecmps-dev.app.cloud.gov
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout devops repo
        uses: actions/checkout@v2
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Setup & Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@us-epa-camd'
      - name: Configure Env Vars
        run: devops/scripts/environment-variables.sh
        env:
          ENV_VAR_PREFIX: REACT_APP_EASEY
      - name: Build
        run: devops/scripts/yarn/build.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Unit Tests
        run: devops/scripts/yarn/unit-tests.sh
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}          
      - name: Install cf cli
        run: devops/scripts/install-cf-cli.sh
      - name: Login to cloud.gov
        run: devops/scripts/cf-login.sh
        env:
          CF_USERNAME: ${{ secrets.CF_DEV_DEPLOYMENT_SVC }}
          CF_PASSWORD: ${{ secrets.CF_DEV_DEPLOYMENT_SVC_PWD }}
      - name: Init Application
        run: devops/scripts/cf-app-init.sh
      - name: Configure Env Vars (secrets)
        run: |
          cf set-env $APP_NAME REACT_APP_ECMPS_API_KEY $REACT_APP_ECMPS_API_KEY
        env:
          REACT_APP_ECMPS_API_KEY: ${{ secrets.ECMPS_NON_PROD_API_KEY }}
      - name: Deploy
        run: devops/scripts/deploy.sh
