name: Develop Branch Workflow

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  Build-Test-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Checkout devops repo
        uses: actions/checkout@v2
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Configure Env Vars
        run: devops/scripts/environment-variables.sh
        env:
          ENV: dev
      - name: Install cf cli
        run: devops/scripts/install-cf-cli.sh
      - name: Login to cloud.gov
        run: devops/scripts/cf-login.sh
        env:
          CF_USERNAME: ${{ secrets.CF_DEV_DEPLOYMENT_SVC }}
          CF_PASSWORD: ${{ secrets.CF_DEV_DEPLOYMENT_SVC_PWD }}
      - name: Build
        run: devops/scripts/build.sh
      # - name: Run Unit Tests
      #   run: devops/scripts/unit-tests.sh
      #   env:
      #     REACT_APP: true
      - name: Deploy
        run: devops/scripts/deploy.sh

  SonarCloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
