name: Feature Branch Workflow

on:
  push:
    branches: [ feature/* ]

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Checkout devops repo
        uses: actions/checkout@v2
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Configure Env Vars
        run: devops/scripts/environment-variables.sh
      - name: Build
        run: devops/scripts/build.sh
      - name: Run Unit Tests
        run: devops/scripts/unit-tests.sh
        env:
          REACT_APP: true

  SonarCloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
