name: Feature Branch Workflow

on:
  pull_request:
    branches: [ develop, release/* ]
    paths-ignore:
    - '**/*.md'
    - 'LICENSE'
    - '.gitignore'

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout devops repo
        uses: actions/checkout@v3
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Setup & Configure Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@us-epa-camd'
      - name: Configure Env Vars
        run: devops/scripts/environment-variables.sh
        env:
          ENV_VAR_PREFIX: REACT_APP_EASEY
      - name: Build
        run: devops/scripts/yarn/build.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Unit Tests
        run: devops/scripts/yarn/unit-tests.sh
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
