name: Develop Branch Workflow

on:
  push:
    branches: [ release/v* ]
  pull_request:
    branches: [ release/v* ]
#    tags:
#      - v[0-9]+.[0-9]+_rc[0-9]+

jobs:
  Build-Test-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Checkout devops repo
        uses: actions/checkout@v2
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Configure Env Vars
        run: devops/scripts/environment-variables.sh
      - name: Install cf cli
        run: devops/scripts/install-cf-cli.sh
      - name: Login to cloud.gov
        run: devops/scripts/cf-login.sh
        env:
          CF_USERNAME: ${{ secrets.CF_SERVICE_ACCOUNT_ID }}
          CF_PASSWORD: ${{ secrets.CF_SERVICE_ACCOUNT_PASSWORD }}
      - name: Build
        run: devops/scripts/build.sh
      - name: Run Unit Tests
        run: devops/scripts/unit-tests.sh
        env:
          REACT_APP: true
      - name: Get Tag
        # may move to bash script!!!
        run: echo "HEAD_TAG=$(git tag --points-at HEAD)" >> $GITHUB_ENV
        # this has been depricated --> echo "::set-env name=HEAD_TAG::$(git tag --points-at HEAD)"
      - name: Package App
        run: devops/scripts/package.sh
      - name: Deploy
        run: devops/scripts/deploy.sh
        env:
          DEPLOY_FROM_ARTIFACT: true

  SonarCloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
