name: Release Branch Workflow

on:
  push:
    branches: [ release/v* ]
  pull_request:
    branches: [ release/v* ]

jobs:
  Build-Test-Package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Checkout devops repo
        uses: actions/checkout@v2
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Build
        run: devops/scripts/build.sh
      - name: Run Unit Tests
        run: devops/scripts/unit-tests.sh
        env:
          REACT_APP: true
      - name: Configure Env Vars
        run: devops/scripts/environment-variables.sh
      - name: Package App
        run: devops/scripts/package.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACTS_STORAGE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACTS_STORAGE_SECRET_ACCESS_KEY }}

  SonarCloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
