name: Test Deployment Workflow

on:
  push:
    tags:
      - tst-v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    tags:
      - tst-v[0-9]+.[0-9]+.[0-9]+

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout devops repo
        uses: actions/checkout@v2
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Configure Env Vars
        run: devops/scripts/environment-variables.sh
        env:
          REACT_APP: true
          DEPLOY_FROM_ARTIFACT: true
      - name: Install cf cli
        run: devops/scripts/install-cf-cli.sh
      - name: Check Tag
        run: devops/scripts/check-tag.sh
      - name: Login to cloud.gov
        run: devops/scripts/cf-login.sh
        env:
          CF_USERNAME: ${{ secrets.CF_TST_DEPLOYMENT_SVC }}
          CF_PASSWORD: ${{ secrets.CF_TST_DEPLOYMENT_SVC_PWD }}
      - name: Deploy
        run: devops/scripts/deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACTS_STORAGE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACTS_STORAGE_SECRET_ACCESS_KEY }}
